### PR TITLE
Support false value

### PR DESCRIPTION
**Pull request by cjmling**
Fix https://github.com/fureweb-com/public-google-sheets-parser/issues/31

### CODE REVIEW

**Comment by fureweb-com** [comment]
Thanks for the work!

Could you add some test code for this work?

**Comment by cjmling** [comment]
@fureweb-com added some test

**Comment by thienhaflash** [comment]
Please get it merged @fureweb-com Even without `false` support it's still good with the `!==undefined` check (works with 0 values).
@fureweb-com @cjmling anyone?

**Comment by fureweb-com** [comment]
I apologize for the delay, I'll make sure to update to version 1.3.3 as soon as possible!

**Pull request merged**
